### ISSUE TITLE
Upgrade build targets

### ISSUE THREAD

**Issue by tpluscode** [r2rml4net/r2rml4net#26]
As @mchaloupka noticed, r2rml4net no longer builds in VS 2017.

@mchaloupka, are we fine with support for `net452`. If Resourcer was replaced with manual handling of embedded resource, we could go down to .NET 4.5.

`netstandard1.5` will only be possible with dotNetRDF 2+. How about that?

Here's what needs to be done:

* [x] convert projects to new csproj format
* [ ] replace StyleCop msbuild task with Roslyn Analyzers
* [x] move unspecified stuff into csproj
* [x] replace Zoltu.Versioning with GitVersion
* [x] also, set up appveyor instead of old TC

**Comment by mchaloupka** [comment]
Is there anything I can help you with this task? It would be really nice for me to convert r2rml4net into netstandard, so even my library (https://github.com/mchaloupka/EVI) can be netstandard then.

**Comment by tpluscode** [comment]
Hi. Sorry about the abandoning this. I started some time ago, encountered some issue and then forgot about it :)

So, I managed to get an almost complete netsdtandard build yesterday. There are some issue. Let me push the changes later today or some time tomorrow to discuss how to resolve the remaining probelems
