### ISSUE TITLE
How to Use FluentR2RML & W3CR2RMLProcessor in complete details

### ISSUE THREAD

**Issue by A7medDaoud** [r2rml4net/r2rml4net#30]
I don't know how to use FluentR2RML & W3CR2RMLProcessor classes.
i want to do the following if possible: 
1- Read .ttl file containing R2RML custom mappings.
2- provide the sql connection to the sql server db.
3- generate all the triples from DB based on the .ttl file
4- store the triples in a triple store (either as a dump or in memory).
5- query the triples using a sparql end point.

I'm using ASP.NET MVC Web Application.
if this is not possible how i can provide the mappings manually in the code.

**Comment by mchaloupka** [comment]
You can use the following code:
```
IR2RML mapping;
using (var fs = new FileStream(path, FileMode.Open))
{
    mapping = R2RMLLoader.Load(fs);
}
```
This code is taken from EVI server which uses this library to load the mapping. See https://github.com/mchaloupka/EVI-SampleServer

That server provides a SPARQL endpoint but using a different approach. It uses transformation from SPARQL to SQL to query the relational data directly (without the need to create a dump). However, that is work in progress. Check out the library which does that: https://github.com/mchaloupka/EVI

**Comment by A7medDaoud** [comment]
Thank you for your reply ,
how i can use this mapping for generating rdf triples (actual data) from the database, storing them into a triple store and  querying them. 
i have tried this but it doe not work.

 IDbConnection iDbConnection = new SqlConnection(connectionString);
W3CR2RMLProcessor _triplesGenerator = new W3CR2RMLProcessor(iDbConnection);
var tripleStore = _triplesGenerator.GenerateTriples(mapping);
var tripless = tripleStore.Triples;

**Comment by A7medDaoud** [comment]
this is the r2rml4net version that i'm using 
"r2rml4net -Version 0.5.0-beta"
when i navigate to the **W3CR2RMLProcessor** calss i found this error 

![Capture](https://user-images.githubusercontent.com/46829565/57167895-beff4800-6dff-11e9-8f79-c4e0016692be.JPG)

and when i navigate to the same code in it at GitHub i found that the code is totally changed 
it seems that the code changed since the last build
 
![Capture2](https://user-images.githubusercontent.com/46829565/57168060-6bd9c500-6e00-11e9-9193-8cd45ac024c4.JPG)
